apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.server.service.servicePort }}
      targetPort: {{ .Values.server.service.apiPort }}
      protocol: TCP
      name: api