---
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      DOMAIN: server.${DOMAIN}
      SECRET_KEY: ${SECRET_KEY}
      ENDORSER_MULTIKEY: ${ENDORSER_MULTIKEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`demo.${DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.server.port=5000

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    environment:
      DOMAIN: server.${DOMAIN}
      SECRET_KEY: ${SECRET_KEY}
      ENDORSER_MULTIKEY: ${ENDORSER_MULTIKEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`server.${DOMAIN}`)
      - traefik.http.routers.server.entrypoints=web
      - traefik.http.services.server.loadbalancer.server.port=8000

  agent:
    build:
      context: https://github.com/hyperledger/aries-cloudagent-python.git
      dockerfile: docker/Dockerfile
    entrypoint: ["aca-py", "start"]
    command: [
      '--no-ledger',
      '--no-transport',
      '--auto-provision',
      '--seed', '${ENDORSER_SEED}',
      '--wallet-type', 'askar',
      '--wallet-name', 'askar',
      '--wallet-key', 'askar',
      '--admin', '0.0.0.0', '8020',
      '--admin-insecure',
    ]
    labels:
      - traefik.enable=true
      - traefik.http.routers.endorser.rule=Host(`agent.${DOMAIN}`)
      - traefik.http.routers.endorser.entrypoints=web
      - traefik.http.services.endorser.loadbalancer.server.port=8020

  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro